### ISSUE TITLE
Incorrect error response format from DFSP CC Server in case of invalid request

### ISSUE THREAD

**Issue by geka-evk** [mojaloop/mifos-core-connector#15]
Here's a definition of expected error response in case of bad request:
https://github.com/mojaloop/mifos-core-connector/blob/ft-payer-initiated-transfer/src/api-spec/core-connector-api-spec-dfsp.yml#L34
  ```
    {
        "status":  "3200",
        "message": "Account No Invalid"
    }
  ```

But for now we got internal Hapi error format:
![image](https://github.com/mojaloop/mifos-core-connector/assets/16463615/46070ad3-caa9-46de-b3ba-8f1307e52ffa)

Need to improve error handling to follow provided error format from api-spec.yaml

**Comment by elijah0kello** [comment]
This error is because of a bad poorly formed api request.

It is an error caught by the api request schema validation

**Comment by elijah0kello** [comment]
Fixing this by updating the api specification
